# Generated by Django 4.1.2 on 2022-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Author's Name")),
                ('lastName', models.CharField(max_length=255, verbose_name="Author's Last Name")),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=100, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('email', models.EmailField(max_length=60, verbose_name='Gmail')),
                ('status', models.BooleanField(default=True, verbose_name='Author On, Author Off')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status On/Status Off')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
