# Generated by Django 4.1.2 on 2022-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extract',
            field=models.CharField(default='short', max_length=100, verbose_name='Extract'),
        ),
    ]
