# Generated by Django 4.1.2 on 2022-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_extract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extract',
            field=models.CharField(max_length=100, verbose_name='Extract'),
        ),
    ]
